name: Build
on: push

env:
  # mojang
  VERSION_MANIFEST: https://piston-meta.mojang.com/mc/game/version_manifest_v2.json

  # project
  GAME: temp/game

  # workflow
  GAME_VERSION_TYPE: snapshot

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Install dependencies project
        run: |
          sudo apt update
          sudo apt install libarchive-tools

          bun install

      - name: Setup game
        run: bun setup-game ${{ env.GAME_VERSION_TYPE }}

      - name: Build
        run: bun run build
